language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -e .[test]
  - pip install .

script:
  - python -m unittest discover