language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install codecov
  - pip install coverage
  - pip install -e .[test]
  - pip install .

script:
  - coverage run --omit="tests/*" -m unittest discover

after_success:
  - codecov
