name: Build test

on:
  push:
    paths-ignore:
    - "**.md"
  pull_request:
    paths-ignore:
    - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # before script
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel codecov coverage
    - name: Install moceansdk
      run: |
        cd "$GITHUB_WORKSPACE"
        pip install -e .[test]
        pip install .
    # run tests
    - name: Run unit test
      run: |
        coverage run --omit="tests/*" -m unittest discover
    - name: Upload code coverage
      if: ${{ matrix.python-version == '3.11' }}
      run: |
        codecov

